version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lndboss_web_1
      APP_PORT: 8055
  
  web:
    image: niteshbalusu/lndboss:v2.9.2@sha256:ab797d7998e1a2f6b81044f34c1df77396e0020488387915411a1801a3ee11cd
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/home/node/.lnd:ro
      - ${APP_DATA_DIR}/.bosgui:/home/node/.bosgui
    environment:
      BOS_DATA_PATH: "/home/node/.bosgui"
      NODE_ENV: "production"
      PORT: 8055
      BOS_DEFAULT_LND_SOCKET: $APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT
